# Run linting and mypy on commits and pull requests
name: Code Quality

on: [push, pull_request]

jobs:
  code-quality:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8, 3.12]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - uses: yezz123/setup-uv@v4

      - name: Install code quality checking dependencies
        run: |
          uv pip install ruff mypy

      - name: Run mypy
        run: mypy gqlrequests

      - name: Run ruff
        run: ruff check .
