# Run pytests and generate coverage
name: Pytests and Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pytests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.8", "3.12"]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package dependencies
        run: pip install pydantic pydantic-settings

      - name: Install testing dependencies
        run: pip install pytest

      - name: Run pytest
        run: python -m pytest tests

  coverage:
    runs-on: ubuntu-latest
    needs: [pytests]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install package dependencies
        run: pip install pydantic

      - name: Install testing and coverage dependencies
        run: pip install pytest pytest-cov

      - name: Run pytest
        run: python -m pytest --cov=gqlrequests --cov-report=xml tests

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          verbose: true
          file: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
