# Run pytests and generate coverage
name: Pytests and Coverage

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  pytests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8, 3.10, 3.12]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install library dependencies
        run: |
          python -m pip install --upgrade pip
          pip install typing-inspect

      - name: Install testing dependencies
        run: |
          pip install pytest

      - name: Run pytest
        run: python -m pytest tests

  coverage:
    runs-on: ubuntu-latest
    needs: [pytests]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - uses: yezz123/setup-uv@v4

      - name: Install library dependencies
        run: |
          uv pip install typing-inspect

      - name: Install testing and coverage dependencies
        run: |
          uv pip install pytest pytest-cov

      - name: Run pytest
        run: python -m pytest --cov=gqlrequests --cov-report=xml tests

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
