# Run pytests and generate coverage
name: Pytests and Coverage

on: [push, pull_request]

jobs:
  pytests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7, 3.9, 3.11]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}}

      - name: Install library dependencies
        run: |
          python -m pip install --upgrade pip
          pip install typing-inspect

      - name: Install testing dependencies
        run: |
          pip install pytest

      - name: Run pytest
        run: pytest
  
  coverage:
    runs-on: ubuntu-latest
    requires: [pytests]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov 

      - name: Run pytest
        run: pytest --cov=gqlrequests --cov-report=xml tests/

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml